replicaCount: 2

appImage: $APP_IMAGE
# dev: 192.168.84.20:8082/utm-builder:dev-latest
# main: juronja/utm-builder:latest

namespace: $K8S_NAMESPACE
dockerSecrets: docker-secrets

frontendService:
  name: ub-app
  containerPort: 3000
  servicePort: 3131
  env:
  - name: MONGO_ADMIN_USER
    valueFrom:
      secretKeyRef:
        name: mongo-admin
        key: MONGO_ADMIN_USER
  - name: MONGO_ADMIN_PASS
    valueFrom:
      secretKeyRef:
        name: mongo-admin
        key: MONGO_ADMIN_PASS
  # resources:
  #   requests:
  #     cpu: 100m
  #     memory: 64Mi
  #   limits:
  #     cpu: 200m
  #     memory: 128Mi

databaseService:
  name: ub-mongodb
  containerPort: 27017
  servicePort: 27017
  env:
  - name: MONGO_INITDB_ROOT_USERNAME
    valueFrom:
      secretKeyRef:
        name: mongo-admin
        key: MONGO_ADMIN_USER
  - name: MONGO_INITDB_ROOT_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mongo-admin
        key: MONGO_ADMIN_PASS
  # resources:
  #   requests:
  #     cpu: 70m
  #     memory: 200Mi
  #   limits:
  #     cpu: 125m
  #     memory: 256Mi
